### ISSUE TITLE
More information needed on use of handlers

### ISSUE THREAD

**Issue by fangjun336699** [barneydobson/wsi#12]
For example, if I am writing a custom handler:
`self.push_set_handler['Land'] = self.push_set_land`

When the land node pushes to my new node, it still goes via the default handler, not the 'Land' handler.

**Comment by fangjun336699** [comment]
Thank you @barneydobson I have read the tutorial and opened it in the Spyder to run it.
It is very clear for the explanation step by step, especially from step '2. Update reservoir handlers' to step '
3. Update my_fwtw to pull with 'FWTW' tag' in the More realistic example. Even if I have understood what it means in the 
Illustration, I still made the same mistake here. It is very worth having a look at both the illustration and the realistic example.

Some points may be useful for the people who are reading this tutorial (if you get confused like when I first read the code)
1. push_set_handler and the other three handlers are actually the 'dictionary'. That is why it can be written like it 'my_dist.push_check_handler['Node'] = custom_handler_function' and overwritten in step '2. Update reservoir handlers'
2. For In[3], '{'volume' : 10,  'phosphate' : 1,  'temperature' : 10}' this is actually a vqip required for the function 'send_push_check'
3. If someone uses the button 'run current cell and go to the next one', you may meet some confusion as I did. (1) some value is not the same as in the tutorial because you may run the cell twice or more times. (2) If you skip the Illustration code and start to run the realistic example directly, you will meet the error 'name 'Arc' is not defined'. This is because I didn't run the cell 'from wsimod.arcs.arcs import Arc'

I think one question at this moment, why do we need to set 'end_timestep' in the step '2. Update reservoir handlers'?
(I may meet more problems when I really start to make a custom handler, but at this moment, it is very clear)

**Comment by fangjun336699** [comment]
For both, I assume they should be very similar

**Comment by barneydobson** [comment]
Sorry I'm just trying to understand the confusion I mean - you just want a bit more explanation of why we are calling them right?

**Comment by fangjun336699** [comment]
Yes, for example, for my_demand.end_timestep(), I checked the code, in which the function giving three empty_vqip to three variables. But I am not very sure why we need to run this line of code 'my_demand.end_timestep()'. If there is not this line, how it will happen

**Comment by barneydobson** [comment]
OK updated - thanks for all the help @fangjun336699
